### ISSUE TITLE
Error When Run

### ISSUE THREAD

**Issue by icy17** [Yunlongs/Goshawk#11]
Hi, I just tried to use Goshawk but met some problems.  I set up the environment in Docker, I'm sure the json file exists and not empty. But when I run:
`python3 ./run.py ./openssl`
I got:
<img width="439" alt="image" src="https://github.com/Yunlongs/Goshawk/assets/39425646/4ea4827a-f087-4cbc-8f4d-b864f9b87126">

**Comment by icy17** [comment]
And I notice that the `compilation.json` is empty when I try to compile libpcap.
My cmd: 
```
autogen.sh
./configure
CodeChecker log -b "make CC=clang HOSTCC=clang -j4" -o compilation.json
```
the compile results:
<img width="665" alt="image" src="https://github.com/Yunlongs/Goshawk/assets/39425646/0128ebc8-bc72-40f6-a53e-0d120a69e271">

And the compilation.json:
<img width="671" alt="image" src="https://github.com/Yunlongs/Goshawk/assets/39425646/8237fef2-e94a-4288-acf2-cad9b55150c6">
Did I do something wrong?

**Comment by yinluming13579** [comment]
CodeChecker log -b "make -j4" -o compilation.json，you can try it instead of CodeChecker log -b "make CC=clang HOSTCC=clang -j4" -o compilation.json

**Comment by Yunlongs** [comment]
@icy17  This issue seems to the incompatible CFLAGS used for clang, as have not specified the c compiler environment `CC` as clang caused the incompatible CFLAGS are logged. I will locate the actual problems and try to figure out solutions for that case.

**Comment by Yunlongs** [comment]
@icy17 I have tested the OpenSSL and there was no error occured?  In OpenSSL, were you configured the compiler of OpenSSL as "clang" ? 
In OpenSSL, the compilation.json should be extracted by the following commands:
```
cd openssl
./configure CC=clang HOSTCC=clang
CodeChecker log -b "make CC=clang HOSTCC=clang -jN" -o compilation.json
```

**Comment by Yunlongs** [comment]
closed. checked with no error occurred.
