### ISSUE TITLE
Step_3_Free  did not generate the file temp/free_check.txt

### ISSUE THREAD

**Issue by WhereIsOops** [Yunlongs/Goshawk#3]
My test code is as follow:
`#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
struct auth{
        char name[32];
        int auth;
};

void free_s(void * ptr)
{
        return free(ptr);
}

void uaf()
{
        printf("enter uaf demo\n");
        int size = 100;
        struct auth *pauth = malloc(100);
        if (!pauth)
        {
                fprintf(stderr, "%s\n", strerror(errno));
                exit(EXIT_FAILURE);
        }
        pauth->auth = 1;

        free_s(pauth);

        if (pauth && pauth->auth){

                printf("uaf success\n");
        }
}

void double_free()
{
        printf("enter double free demo\n");
        int size = 100;
        void *ptr = malloc(100);
        if (!ptr)
        {
                fprintf(stderr, "%s\n", strerror(errno));
                exit(EXIT_FAILURE);
        }

        free(ptr);
        free(ptr);
}

int main()
{
        uaf();
        double_free();
}
`
An error occurred while running goshawk

extracting time: 0.44608020782470703
Call Graph read finished!
 total func number:9
clang -fsyntax-only -Xclang -load -Xclang /home/Goshawk/plugins/FreeNullCheck.so -Xclang -plugin -Xclang free-check -Xclang -plugin-arg-free-check -Xclang /home/Goshawk/temp/candidate_free.txt -Xclang -plugin-arg-free-check  -Xclang /home/Goshawk/temp/free_check.txt -Xclang -plugin-arg-free-check  -Xclang /home/Goshawk/temp/visited.txt -c test.c -o test.o
Traceback (most recent call last):
  File "/home/Goshawk/run.py", line 251, in <module>
    Step_3_Free()
  File "/home/Goshawk/run.py", line 127, in Step_3_Free
    cleanup_free_null_check(config.free_check_file)
  File "/home/Goshawk/utils.py", line 26, in cleanup_free_null_check
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/free_check.txt'

**Comment by Yunlongs** [comment]
Sorry. Goshawk can't obtain enough information to proceed the next step in small script. It is designed to be used on modern project. Maybe you can test Goshawk on some larger project, such as openssl.

**Comment by Yunlongs** [comment]
@WhereIsOops this bug fixed! see in #9 .
