### ISSUE TITLE
clang-16: error: clang frontend command failed with exit code 139

### ISSUE THREAD

**Issue by karling1989** [Yunlongs/Goshawk#5]
您好，我用Goshawk 分析一个简单的文件，
命令：python3 run.py /data/home/hongzheli/test_project_c_20221025/use_after_free_case/
出现如下错误：
![企业微信截图_16698813701542](https://user-images.githubusercontent.com/35992812/204997131-b7604173-dfd3-449b-9092-9ea2d99e9007.png)
请问如何解决呢？

**Comment by Yunlongs** [comment]
The version of pre-built clang plugins is Clang version 15.0.0, if you used incompatible Clang version, crashes in plugins will happen.
