### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'temp/free_check.txt'

### ISSUE THREAD

**Issue by karling1989** [Yunlongs/Goshawk#6]
您好：我用Goshawk分析一个文件（文件名：use_after_free.c）,途中遇到了文件找不到的错误，请教一下大佬如何解决呢？
![企业微信截图_16702300813028](https://user-images.githubusercontent.com/35992812/205596495-5acef935-47d1-4787-8fad-1071521cac3e.png)

**Comment by yinluming13579** [comment]
你好，我也遇到了相同的问题，请问你的问题解决了吗

**Comment by Yunlongs** [comment]
@yinluming13579 针对这种情况，我这几天会做个修复

**Comment by Yunlongs** [comment]
Same issue in #9 and sloved in the least commit.
