### ISSUE TITLE
自己写了一个含有释放后使用简单的cpp文件使用goshawk检查报错

### ISSUE THREAD

**Issue by yinluming13579** [Yunlongs/Goshawk#9]
你好，我自己写了两个c文件，这两个文件都包含一个释放后使用错误，我将文件放到goshawk上去检测，发现goshawk在第三步时提示FileNotFoundError: [Errno 2] No such file or directory: 'temp/free_check.txt'，检测无法成功，下面是我的代码以及部分配置文件信息：
goshawk失败提示：`-----------------------------------------------

Step3: Identify Deallocation Functions from source code Start!
-----------------------------------------------

WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
extracting time: 0.43344902992248535
Call Graph read finished!
 total func number:9
clang -fsyntax-only -Xclang -load -Xclang /project/osteacher/Goshawk/plugins/FreeNullCheck.so -Xclang -plugin -Xclang free-check -Xclang -plugin-arg-free-check -Xclang /project/osteacher/Goshawk/temp/candidate_free.txt -Xclang -plugin-arg-free-check  -Xclang /project/osteacher/Goshawk/temp/free_check.txt -Xclang -plugin-arg-free-check  -Xclang /project/osteacher/Goshawk/temp/visited.txt -Wall -o figure figure.c
clang -fsyntax-only -Xclang -load -Xclang /project/osteacher/Goshawk/plugins/FreeNullCheck.so -Xclang -plugin -Xclang free-check -Xclang -plugin-arg-free-check -Xclang /project/osteacher/Goshawk/temp/candidate_free.txt -Xclang -plugin-arg-free-check  -Xclang /project/osteacher/Goshawk/temp/free_check.txt -Xclang -plugin-arg-free-check  -Xclang /project/osteacher/Goshawk/temp/visited.txt -Wall -o figure1 figure1.c
Traceback (most recent call last):
  File "run.py", line 256, in <module>
    Step_3_Free()
  File "run.py", line 132, in Step_3_Free
    cleanup_free_null_check(config.free_check_file)
  File "/project/osteacher/Goshawk/utils.py", line 26, in cleanup_free_null_check
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/free_check.txt'`
我自己为两个c文件写的makefile：
`CC = gcc
CFLAGS = -Wall

all: figure figure1

figure: figure.c
	$(CC) $(CFLAGS) -o figure figure.c

figure1: figure1.c
	$(CC) $(CFLAGS) -o figure1 figure1.c

clean:
	rm -f figure figure1`
一个含有释放后使用漏洞的代码：
`#include <stdlib.h>
#include <stdio.h>

typedef struct node {
	int val;
	struct node *next;
} Node;

Node* create() {
	return (Node*)
	  malloc(sizeof(Node));
}

void myfree(Node **n) {
	free(*n);
	*n = NULL;
}

int main() {
	Node *n1, *n2;
	n1 = create();
	n1->val = 10;
	n2 = create();
	n2->val = 5;   
	int y, i = 0;
	scanf("%d", &y);

	while (y < 10) {
		int x;
		scanf("%d", &x);

		while (x > 10) {
			i++;
			if (i > 4)
				x += i;
			else
				x -= i;

			if (x % 2 == 0)
				n2 = n1;
		}

		y += x;
	}

	myfree(&n1);
	printf("%d", n2->val);
	myfree(&n2);
}
`
生成的compilation.json文件：
`[
	{
		"directory": "/project/osteacher/test_case",
		"command": "/usr/local/bin/clang -Wall -o figure figure.c",
		"file": "figure.c"
	}
	,
	{
		"directory": "/project/osteacher/test_case",
		"command": "/usr/local/bin/clang -Wall -o figure1 figure1.c",
		"file": "figure1.c"
	}
]`

**Comment by yinluming13579** [comment]
您好，我看您在之前的回复中说是因为项目的规模太小导致程序无法获得足够的信息，请问您能具体说说是什么样的信息获取不足吗？信息不足则不生成文件具体在代码的哪部分呢？还想再向您请教一下刚刚我试了一下测试redis，好像按照openssl的方式不能成功生成compliation.josn文件，您能给出测试redis需要的指令吗？

**Comment by Yunlongs** [comment]
@yinluming13579 要获取的信息是mem alloc/dealloc 函数可能的wrapper，这些函数会作为candidates 进行静态分析。目前没有考虑到获取不到这些信息的情况，后面会改善下这相关的逻辑。将redis项目的编译指令，内嵌在
`CodeChecker log -b "[compilation instruction]" -o compilation.json` 引号中，即可生成compilation.json。
更详细的用法见：https://github.com/Ericsson/codechecker/blob/master/docs/usage.md#log-your-build

**Comment by yinluming13579** [comment]
非常感谢您能够从百忙之中抽出时间来修复这个项目规模太小无法检测问题，这个问题困扰我很久了，感谢！！期待项目的更新！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yunlongs/Goshawk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yunlongs/Goshawk] 自己写了一个含有释放后使用简单的cpp文件使用goshawk检查报错 (Issue #9)





 
@yinluming13579 要获取的信息是mem alloc/dealloc 函数可能的wrapper，这些函数会作为candidates 进行静态分析。目前没有考虑到获取不到这些信息的情况，后面会改善下这相关的逻辑。将redis项目的编译指令，内嵌在
 CodeChecker log -b "[compilation instruction]" -o compilation.json 引号中，即可生成compilation.json。
 更详细的用法见：https://github.com/Ericsson/codechecker/blob/master/docs/usage.md#log-your-build

**Comment by Yunlongs** [comment]
@yinluming13579 hi, the FileNotFoundError is fixed.

**Comment by Yunlongs** [comment]
@yinluming13579 The problem with redis is this error?
```In file included from adlist.c:34:
zmalloc.h:50:10: fatal error: jemalloc/jemalloc.h: No such file or directory
   50 | #include <jemalloc/jemalloc.h>
```

**Comment by yinluming13579** [comment]
> @yinluming13579 The problem with redis is this error?
> 
> ```
> zmalloc.h:50:10: fatal error: jemalloc/jemalloc.h: No such file or directory
>    50 | #include <jemalloc/jemalloc.h>
> ```

谢谢你的修复！Redis的错误我印象中还没运行到你说的这一步，看了你先前的回复我应该是没有正确设置codechecker的参数导致的，之后几天我会再试一下去跑Redis，看看能不能正确检测。

**Comment by Yunlongs** [comment]
> 
@yinluming13579 
Hi, i found the issue about error logging compilation database for redis might be the missing build dependency of redis. Before you logging compilation database by CodeChecker, you should build redis first. The following were the instructions that i logged it successfully:

```
cd path/to/redis
make
make clean
CodeChecker log -b "make" -o compilation.json
```

**Comment by yinluming13579** [comment]
> > 
> 
> @yinluming13579 Hi, i found the issue about error logging compilation database for redis might be the missing build dependency of redis. Before you logging compilation database by CodeChecker, you should build redis first. The following were the instructions that i logged it successfully:
> 
> ```
> cd path/to/redis
> make
> make clean
> CodeChecker log -b "make" -o compilation.json
> ```

好的好的！谢谢！
